disabled_rules:
  - type_body_length
  - file_length
  - type_name
  - line_length
  - force_cast
  - force_try
  - legacy_constructor
included:
excluded:
  - Carthage
  - Dollar
  - Pods
  - Packages
